// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rqazbfxfugmiyxppqmoj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJxYXpiZnhmdWdtaXl4cHBxbW9qIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIxOTQ2NTUsImV4cCI6MjA2Nzc3MDY1NX0.cS0GeS5t6QISZhJvXyRseQxvwfM5JFVtsOUExSN881Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});